style: accessibility improvements to high contrast and text size
huynhsontung/Screenbox pull request #377
Opened 2024-05-15 17:53 UTC by United600

## Describe your changes

- Adds visual feedback to ListView/GridView headers

**Before**

https://github.com/huynhsontung/Screenbox/assets/698155/f6b556c9-9f7a-47d9-bebb-34b2fca2bf14 

**After**

https://github.com/huynhsontung/Screenbox/assets/698155/03a221fb-28e8-40d1-a012-1e638dd073a2

- Improved accessibility text size support

> [!NOTE]
> This area still needs more work.

https://github.com/huynhsontung/Screenbox/assets/698155/b01e7f63-c36e-4746-aae6-5f2d04957d71

https://github.com/huynhsontung/Screenbox/assets/698155/5acbc4c8-c609-403d-878f-cdf266ad7f96

- Tweaked GridViewItem design (for both High Contrast and Dark/Light theme)

**Before**

https://github.com/huynhsontung/Screenbox/assets/698155/4990f4f1-9b05-447a-94f9-c9bbf223c1f6

**After**

https://github.com/huynhsontung/Screenbox/assets/698155/95b248ea-fef2-4f7c-b569-75820512c4f4

- Adds margins between ListView item on Windows 10
- Improvements to GridViewItem hover state on Windows 10
- High Contrast improvements to ListViewItem/GridViewItem TextBlock hover/press state
- Fix some theme switching problems

https://github.com/huynhsontung/Screenbox/assets/698155/79b7c2ce-9eea-4ab2-8c13-65b7df68d195

https://github.com/huynhsontung/Screenbox/assets/698155/4e6d670e-4963-4202-8d62-8f570abd3cf4

2024-05-16 05:02 UTC, huynhsontung requested changes
Thank you for all these changes. We still need a bit of discussion in some areas before we can merge this.

2024-05-16 05:02 UTC, huynhsontung commented on Screenbox/Pages/NetworkPage.xaml
> +            <RowDefinition MinHeight="40" />
Layout issue detected
![image](https://github.com/huynhsontung/Screenbox/assets/31434093/af5e4225-4082-483d-93cf-c50d0afb2baf)

This is due to Row defaults to use star sizing if not specified I think.
```suggestion
            <RowDefinition Height="Auto" MinHeight="40" />
```

2024-05-16 05:02 UTC, huynhsontung commented on Screenbox/Styles/ItemContainer.xaml
> +            <x:Double x:Key="TextFillColorTertiaryOpacity">0.53</x:Double>
I love this. This is so clever! 🤩

2024-05-16 05:02 UTC, huynhsontung commented on Screenbox/Styles/ItemContainer.xaml
> +                                </VisualState>
Why do we use Storyboard here? Shouldn't `VisualState.Setters` be enough here? It doesn't seem like any animation is playing.

2024-05-16 05:02 UTC, huynhsontung commented on Screenbox/Styles/ItemContainer.xaml
> +    <Style x:Key="ListViewHeaderItemSubtleButtonStyle" TargetType="ListViewHeaderItem">
How is this style different from the `GridViewHeaderItemSubtleButtonStyle`?

2024-05-16 05:02 UTC, huynhsontung commented on Screenbox/Styles/ItemContainer.xaml
> +                            <BrushTransition />
Regular list view items don't have transition animations for PointerOver and Pressed state. It feels a bit out of place imo.

Due to the animation delay, the button doesn't feel tactile. If we want to have animations for PointerOver and Pressed state then we should take Ambie's as a reference. Windows 11 uses this transition in its taskbar as well.

https://github.com/huynhsontung/Screenbox/assets/31434093/a6a88279-0e7a-4b46-a07b-b5206baa80ea

2024-05-16 22:51 UTC, United600 commented on Screenbox/Pages/NetworkPage.xaml
> +            <RowDefinition MinHeight="40" />
Oops. It's always this page.

2024-05-16 23:00 UTC, United600 commented on Screenbox/Styles/ItemContainer.xaml
> +    <Style x:Key="ListViewHeaderItemSubtleButtonStyle" TargetType="ListViewHeaderItem">
The `GridViewHeaderItemSubtleButtonStyle` needs a plus 4 side margin to compensate for this (so it's inline with the content):
https://github.com/huynhsontung/Screenbox/blob/a93c9377b12c2756bb1a53a759ef276a876cc37b/Screenbox/App.xaml#L89

2024-05-16 23:02 UTC, United600 commented on Screenbox/Styles/ItemContainer.xaml
> +                            <BrushTransition />
I'll remove the transition. I mostly copied the button template but I guess it makes more sense to behave, as closely as possible, like the ListViewItem/GridViewItem.

2024-05-16 23:06 UTC, United600 commented on Screenbox/Styles/ItemContainer.xaml
> +                                </VisualState>
Hmmm, is there any penalty that I'm not aware? Aren't 0 time duration animations as performant as they can get? Semms like the default for WinUI/SystemXAML.

2024-05-18 02:27 UTC, huynhsontung commented on Screenbox/Styles/ItemContainer.xaml
> +    <Style x:Key="ListViewHeaderItemSubtleButtonStyle" TargetType="ListViewHeaderItem">
In that case, you can probably base one style on the other and just override the different values.

```xaml
<Style x:Key="GridViewHeaderItemSubtleButtonStyle" TargetType="GridViewHeaderItem" BasedOn="ListViewHeaderItemSubtleButtonStyle">
```

If that doesn't work you can change the TargetType to `ListViewBaseHeaderItem` so both styles target the same type.

2024-05-29 18:49 UTC, huynhsontung approved these changes
Thank you for this!

2024-05-29 19:37 UTC, merged